kien truc va tkpm/code tmp/BTL_Thay_que/core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('user.urls')),
    path('', include('customer.urls'))
]

kien truc va tkpm/code tmp/BTL_Thay_que/core/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('add-book-cart/', views.add_book_to_cart, name='add-book-cart'),
    path('add-clothes-cart/', views.add_clothes_to_cart, name='add-clothes-cart'),
    path('add-mobile-cart/', views.add_mobile_to_cart, name='add-mobile-cart'),
    path('cart-detail/', views.get_cart, name='cart'),
    path('search-page/', views.get_search_page, name='search-page'),
    path('search/', views.search, name='search'),
    path('search-voice/', views.search_voice, name='search-voice'),
    path('order-form/', views.order_form, name='order-form'),
    path('create-order', views.add_order, name='add-order'),
    path('list-order/', views.get_list_order, name='list-order'),
    path('detail-order/<int:order_id>/', views.detail_order, name='detail-order'),
    path('cancel-order/', views.cancel_order, name='cancel-order'),
]

kien truc va tkpm/code tmp/BTL_Thay_que/core/templates/order/detail-order.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-6 text-3xl">Detail order</h1>
{% load cart_tags %}
<div class="space-y-6">
    {% for item in order.order_product %}
        <div class="p-6 flex bg-gray-100 rounded-xl">
            <div class="pr-6">
                <img src="{{ item.image }}" class="w-20 rounded-xl">
            </div>

            <div>
                <p class="text-2xl">{{ item.title }}</p>
                <p class="text-2xl">{{ item.name }}</p>
                <p class="text-xl text-gray-500">Đơn giá {{ item.price|number_format }} đ</p>
                <p class="text-xl text-gray-500"> Số lượng: {{ item.quantity }}</p>
                <p class="text-xl text-green-500"> Thành tiền: {{ item.total_price|number_format }} đ</p>
            </div>
        </div>
    {% endfor %}
    <p class="text-3xl text-green-700 font-bold">Tổng tiền: {{ order.total_price|number_format }} đ</p>
    <p class="text-3xl text-gray-500 font-bold">Thời gian đặt hàng: {{ order.date|custom_date_format }}</p>
    <p class="text-3xl text-gray-500 font-bold">
        Trạng thái: 
        {% if order.isDone == True %}
            <span class="text-green-500"> Done</span>
        {% else %}
            {% if order.approved == True %}
                <span class="text-orange-500"> Approved - Delivering</span>
            {% else %}
                <span class="text-red-500"> Unapproved</span>
            {% endif %}
        {% endif %}
    </p>
    {% if order.approved == True %}
    <button class="toggleButton inline-block mt-6 ml-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-blue-700">View detail</button>
    {% else %}
    <form action="{% url 'customer:cancel-order' %}" method="POST" onsubmit="return confirm('Are you sure cancel this order?')">
        {% csrf_token %}
        <input type="hidden" name="order_id" value="{{ order.id }}">
        <button type="submit" class="px-6 py-3 font-bold rounded-xl bg-red-500 hover:bg-red-700 text-white my-5">Cancel Order</button>
    </form>
    {% endif %}
    <div class="overlay"></div>
    <div class="popup">
        
        {% for status in shipment_status.shipment_status %}
            <div class="w-full mx-6 my-6">
                <p class="text-gray-500">{{ status.time|custom_datetime_format }}</p>
                <p>{{ status.shipment_status }}</p>
            </div>
            
        {% endfor %}
            
        <button class="closeButton px-3 py-2 bg-red-500 rounded-xl text-lg text-white bordered">X</button>
    </div>
    
</div>
{% endblock content %}

kien truc va tkpm/code tmp/BTL_Thay_que/core/templates/order/ds-order.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ds hóa đơn</title>
<script src="https://cdn.tailwindcss.com"></script>
</head>
{% load cart_tags %}
<body>
    {% if ds_order|length == 0 %}
        <div class="flex justify-center items-center">
            <h1 class="mb-6 text-5xl px-6 mt-6">Chưa có order nào!</h1>
        </div>
    {% endif %}
	<div class="my-5 text-center">
        <a href="javascript:history.back()" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Quay lại</a>
    </div>
    {% for order in ds_order %}
	<div class="flex justify-center items-center">
        <div class="px-6 text-center">
            <div class="w-full">
                <a href="{% url 'customer:detail-order' order.id %}" class="px-5">
                    <div class="pr-6 flex bg-gray-100 rounded-xl justify-between items-center h-24">
                        <div class="pr-6">
                            <p class="text-4xl px-6 text-4xl px-6 text-gray-500">
                                {{ order.date|custom_date_format }}
                            </p>
                        </div>
                        <p>Total price: {{ order.total_price|number_format }} đ</p>
                        <div class="pr-6">
                            <p class="text-xl px-6">
                                {% if order.isDone == True %}
                                    <span class="text-green-500"> Done</span>
                                {% else %}
                                    {% if order.approved == True %}
                                        <span class="text-orange-500">Delivering</span>
                                    {% else %}
                                        <span class="text-red-500"> Unapproved</span>
                                    {% endif %}
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </a>
            </div>
        </div>
	</div>
    {% endfor %}
</body>

</html>