kien truc va tkpm/CODE/DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('product/', include('product.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
    path('clothes/', include('clothes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kien truc va tkpm/CODE/DjangoProject/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('<int:pk>/add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('carts/', views.carts, name='carts'),
]

kien truc va tkpm/CODE/DjangoProject/clothes/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'clothes'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail',)
]

kien truc va tkpm/CODE/DjangoProject/mobile/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail',)
]

kien truc va tkpm/CODE/DjangoProject/search/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.products, name='products'),
    path('voice/', views.productsByVoice, name='products-voice'),
]

kien truc va tkpm/CODE/DjangoProject/templates/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | bookstore</title>
        <style>
            /* Ẩn popup và overlay mặc định */
            .popup {
                display: none;
                position: fixed;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                padding: 20px;
                max-height: 80%;
                overflow-y: auto;
                background-color: #fff;
                border: 1px solid #ccc;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
                opacity: 0;
                transition: opacity 0.3s;
                z-index: 2;
            }
    
            /* Tạo hiệu ứng mờ nền khi popup hiển thị */
            .overlay {
                display: none;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0, 0, 0, 0.5);
                opacity: 0;
                transition: opacity 0.3s;
                z-index: 1;
            }
    
            /* Nút đóng ở vị trí cố định */
            .closeButton {
                position: fixed;
                top: 10px;
                right: 10px;
                cursor: pointer;
            }
        </style>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Bookstore</a>

            <div class="space-x-6">
                <a href="#" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="{% url 'search:products' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'cart:carts' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                        Cart
                        
                    </a>
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                {% else %}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
        <script>
            var popups = document.querySelectorAll('.popup');
            var overlays = document.querySelectorAll('.overlay');
            var toggleButtons = document.querySelectorAll('.toggleButton');
            var closeButtons = document.querySelectorAll('.closeButton');
    
            toggleButtons.forEach(function (toggleButton, index) {
                toggleButton.addEventListener('click', function () {
                    popups[index].style.display = 'block';
                    overlays[index].style.display = 'block';
    
                    // Thêm lớp active để kích hoạt hiệu ứng sáng lên
                    setTimeout(function () {
                        popups[index].style.opacity = 1;
                        overlays[index].style.opacity = 1;
                    }, 10);
                });
            });
    
            closeButtons.forEach(function (closeButton, index) {
                closeButton.addEventListener('click', function () {
                    // Gán lại giá trị mặc định cho opacity để kích hoạt hiệu ứng biến mất
                    popups[index].style.opacity = 0;
                    overlays[index].style.opacity = 0;
    
                    // Ẩn popup và overlay sau khi hoàn thành hiệu ứng biến mất
                    setTimeout(function () {
                        popups[index].style.display = 'none';
                        overlays[index].style.display = 'none';
                    }, 300);
                });
            });
    
            overlays.forEach(function (overlay, index) {
                overlay.addEventListener('click', function () {
                    // Khi người dùng nhấp vào overlay, ẩn popup và overlay
                    popups[index].style.opacity = 0;
                    overlays[index].style.opacity = 0;
    
                    setTimeout(function () {
                        popups[index].style.display = 'none';
                        overlays[index].style.display = 'none';
                    }, 300);
                });
            });
        </script>
        
    </body>
</html>

kien truc va tkpm/CODE/DjangoProject/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">List Book</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for product in products %}
                <div>
                    <a href="{% url 'product:detail' product.id %}">
                        <div>
                            <img src="{{ product.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ product.name }}</h2>
                            <p class="text-gray-500">Price: {{ product.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

        <h2 class="mb-12 text-2xl text-center">List Clothes</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for cloth in clothes %}
                <div>
                    <a href="{% url 'clothes:detail' cloth.id %}">
                        <div>
                            <img src="{{ cloth.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ cloth.name }}</h2>
                            <p class="text-gray-500">Price: {{ cloth.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

        <h2 class="mb-12 text-2xl text-center">List Mobiles</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for mobile in mobiles %}
                <div>
                    <a href="#">
                        <div>
                            <img src="{{ mobile.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ mobile.name }}</h2>
                            <p class="text-gray-500">Price: {{ mobile.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.products.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}