kien truc va tkpm/code tmp/BTL_Thay_que/core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('user.urls')),
    path('', include('customer.urls'))
]

kien truc va tkpm/code tmp/BTL_Thay_que/core/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('add-book-cart/', views.add_book_to_cart, name='add-book-cart'),
    path('add-clothes-cart/', views.add_clothes_to_cart, name='add-clothes-cart'),
    path('add-mobile-cart/', views.add_mobile_to_cart, name='add-mobile-cart'),
    path('cart-detail/', views.get_cart, name='cart'),
    path('search-page/', views.get_search_page, name='search-page'),
    path('search/', views.search, name='search'),
    path('search-voice/', views.search_voice, name='search-voice'),
    path('order-form/', views.order_form, name='order-form'),
    path('create-order', views.add_order, name='add-order'),
    path('list-order/', views.get_list_order, name='list-order'),
    path('detail-order/<int:order_id>/', views.detail_order, name='detail-order'),
    path('cancel-order/', views.cancel_order, name='cancel-order'),
]

kien truc va tkpm/code tmp/BTL_Thay_que/core/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    
    path('', views.get_home, name='home'),
    path('login-form/', views.login_form, name='login-form'),
    path('check-user/', views.check_login, name='check-login'),
    path('logout/', views.logout, name='logout'),
    path('book/<int:book_id>/', views.detail_book, name='detail-book'),
    path('clothes/<int:clothes_id>/', views.detail_clothes, name='detail-clothes'),
    path('mobile/<int:mobile_id>/', views.detail_mobile, name='detail-mobile'),
]

kien truc va tkpm/code tmp/BTL_Thay_que/core/templates/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>ecom system</title>
        <style>
            /* Ẩn popup và overlay mặc định */
            .popup {
                display: none;
                position: fixed;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                padding: 20px;
                max-height: 80%;
                overflow-y: auto;
                background-color: #fff;
                border: 1px solid #ccc;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
                opacity: 0;
                transition: opacity 0.3s;
                z-index: 2;
            }
    
            /* Tạo hiệu ứng mờ nền khi popup hiển thị */
            .overlay {
                display: none;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0, 0, 0, 0.5);
                opacity: 0;
                transition: opacity 0.3s;
                z-index: 1;
            }
    
            /* Nút đóng ở vị trí cố định */
            .closeButton {
                position: fixed;
                top: 10px;
                right: 10px;
                cursor: pointer;
            }
        </style>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">ECOM SYSTEM</a>

            <div class="space-x-6">
                {% if request.session.user %}
                    {% if request.session.user.role == 'customer' %}
                        <a href="{% url 'customer:search-page' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                        <a href="{% url 'customer:cart' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Cart</a>
                        <a href="{% url 'customer:list-order' %}" class="px-6 py-3 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">Your Order</a>
                {% endif %}
                {% if request.session.user.role == 'employee' %}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Approve Order</a>
                {% endif %}
                {% if request.session.user.role == 'manager' %}
                    <a href="{% url 'customer:cart' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Dashboard</a>
                {% endif %}
                    <a href="{% url 'user:logout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
                {% else %}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'user:login-form' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        
        <script>
            var popups = document.querySelectorAll('.popup');
            var overlays = document.querySelectorAll('.overlay');
            var toggleButtons = document.querySelectorAll('.toggleButton');
            var closeButtons = document.querySelectorAll('.closeButton');
    
            toggleButtons.forEach(function (toggleButton, index) {
                toggleButton.addEventListener('click', function () {
                    popups[index].style.display = 'block';
                    overlays[index].style.display = 'block';
    
                    // Thêm lớp active để kích hoạt hiệu ứng sáng lên
                    setTimeout(function () {
                        popups[index].style.opacity = 1;
                        overlays[index].style.opacity = 1;
                    }, 10);
                });
            });
    
            closeButtons.forEach(function (closeButton, index) {
                closeButton.addEventListener('click', function () {
                    // Gán lại giá trị mặc định cho opacity để kích hoạt hiệu ứng biến mất
                    popups[index].style.opacity = 0;
                    overlays[index].style.opacity = 0;
    
                    // Ẩn popup và overlay sau khi hoàn thành hiệu ứng biến mất
                    setTimeout(function () {
                        popups[index].style.display = 'none';
                        overlays[index].style.display = 'none';
                    }, 300);
                });
            });
    
            overlays.forEach(function (overlay, index) {
                overlay.addEventListener('click', function () {
                    // Khi người dùng nhấp vào overlay, ẩn popup và overlay
                    popups[index].style.opacity = 0;
                    overlays[index].style.opacity = 0;
    
                    setTimeout(function () {
                        popups[index].style.display = 'none';
                        overlays[index].style.display = 'none';
                    }, 300);
                });
            });
        </script>
        
    </body>
</html>

kien truc va tkpm/code tmp/BTL_Thay_que/core/templates/carts.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-6 text-3xl font-bold text-orange-700">Your cart</h1>
{% load cart_tags %}
<div class="space-y-6">
    {% for book in cart.cart_book %}
        <div class="p-6 flex bg-gray-100 rounded-xl">
            <div class="pr-6">
                <img src="{{ book.image }}" class="w-20 rounded-xl">
            </div>

            <div>
                <p class="text-2xl">{{ book.title }}</p>
                <p class="text-xl text-gray-500">Đơn giá {{ book.price|number_format }} đ</p>
                <p class="text-xl text-gray-500"> Số lượng: {{ book.quantity }}</p>
                <p class="text-xl text-green-500"> Thành tiền: {{ book.total_price|number_format }} đ</p>
            </div>
        </div>
    {% endfor %}

    {% for clothes in cart.cart_clothes %}
        <div class="p-6 flex bg-gray-100 rounded-xl">
            <div class="pr-6">
                <img src="{{ clothes.image }}" class="w-20 rounded-xl">
            </div>

            <div>
                <p class="text-2xl">{{ clothes.name }}</p>
                <p class="text-xl text-gray-500">Đơn giá {{ clothes.price|number_format }} đ</p>
                <p class="text-xl text-gray-500"> Số lượng: {{ clothes.quantity }}</p>
                <p class="text-xl text-green-500"> Thành tiền: {{ clothes.total_price|number_format }} đ</p>
            </div>
        </div>
    {% endfor %}

    {% for mobile in cart.cart_mobile %}
        <div class="p-6 flex bg-gray-100 rounded-xl">
            <div class="pr-6">
                <img src="{{ mobile.image }}" class="w-20 rounded-xl">
            </div>

            <div>
                <p class="text-2xl">{{ mobile.name }}</p>
                <p class="text-xl text-gray-500">Đơn giá {{ mobile.price|number_format }} đ</p>
                <p class="text-xl text-gray-500"> Số lượng: {{ mobile.quantity }}</p>
                <p class="text-xl text-green-500"> Thành tiền: {{ mobile.total_price|number_format }} đ</p>
            </div>
        </div>
    {% endfor %}

    {% if cart.cart_book|length > 0 or cart.cart_clothes|length > 0 or cart.cart_mobile|length > 0 %}
    <p class="text-3xl text-green-700 font-bold">Tổng tiền: {{ total_price|number_format }} đ</p>
    <form action="{% url 'customer:order-form' %}" method="POST" class="text-center">
        {% csrf_token %}
        <input type="hidden" name="cart" value="{{ cart }}">
        <input type="hidden" name="total_price" value="{{ total_price }}">
        <button type="submit" class="px-6 py-3 text-white bg-green-500 hover:bg-green-700 rounded-xl font-bold">Mua ngay</button>
    </form>
    {% else %}
    <p class="text-3xl text-green-700 font-bold">Bạn chưa có sản phẩm nào trong giỏ hàng</p>
    {% endif %}
    
</div>
{% endblock content %}

kien truc va tkpm/code tmp/BTL_Thay_que/core/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}
{% load cart_tags %}
{% block content %}
    <div class="mt-6 px-6 py-12 rounded-xl">
        <h2 class="mb-12 text-5xl text-center font-bold">List Book</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in books %}
                <div class="w-4/5">
                    <a href="{% url 'user:detail-book' item.id %}">
                        <div>
                            <img src="{{ item.image }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.title }}</h2>
                            <p class="text-gray-500">Price: {{ item.price|number_format }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

        <h2 class="mb-12 text-5xl text-center font-bold mt-5">List Clothes</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in clothes %}
                <div class="w-4/5">
                    <a href="{% url 'user:detail-clothes' item.id %}">
                        <div>
                            <img src="{{ item.image }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price|number_format }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

        <h2 class="mb-12 text-5xl text-center font-bold mt-5">List Mobiles</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in mobiles %}
                <div class="w-4/5">
                    <a href="{% url 'user:detail-mobile' item.id %}">
                        <div>
                            <img src="{{ item.image }}" class="rounded-t-xl">
                        </div>
                        <p>{{ item.image.url }}</p>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price|number_format }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

kien truc va tkpm/code tmp/BTL_Thay_que/core/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>login</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
      .password-input {
        position: relative;
      }
      
      .toggle-password {
        position: absolute;
        right: 5px;
        top: 50%;
        transform: translateY(-50%);
        background: none;
        border: none;
        width: 30px;
        height: 30px;
        background-repeat: no-repeat;
        background-size: cover;
        cursor: pointer;
      }
    </style>
  </head>

  <body>
    <div class="px-6 py-6">
      <div class="w-2/5 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"><b>Đăng nhập hệ thống</b></h1>

        <form method="post" action="{% url 'user:check-login' %}">
          {% csrf_token %}
          <div class="mb-3">
            <label class="inline-block mb-2">Số điện thoại <span style="color: red">&#160;(*)</span></label><br /> 
            <input type="text" name="mobile" class="w-full py-2 px-6 rounded-xl" autofocus required />
          </div>

          <div class="mb-3 password-input">
            <label class="inline-block mb-2">Mật khẩu <span style="color: red">&#160;(*)</span></label><br />
            <input type="password" id="passwordInput" name="password" class="w-full py-2 px-6 rounded-xl" required />
            <button type="button" class="toggle-password mt-3 mr-5" onclick="togglePasswordVisibility()"><i id="eyeIcon" class="fa-regular fa-eye"></i></button>
          </div>

          {% if error_message %}
            <p class="text-danger mb-3">{{ error_message }}</p>
          {% endif %}
          <button type="submit" class="py-3 px-3 text-lg bg-teal-500 rounded-xl text-white mx-3">Đăng nhập</button>
          <a href="/" class="py-3 px-3 text-lg bg-red-500 rounded-xl text-white">Về trang chủ</a>
        </form>
      </div>
    </div>
  </body>
  <script>
    function togglePasswordVisibility() {
      var passwordInput = document.getElementById('passwordInput')
      var eyeIcon = document.getElementById('eyeIcon')
      if (passwordInput.type === 'password') {
        passwordInput.type = 'text'
        eyeIcon.className = 'fa-regular fa-eye'
      } else {
        passwordInput.type = 'password'
        eyeIcon.className = 'fa-regular fa-eye-slash'
      }
    }
  </script>
</html>

kien truc va tkpm/code tmp/BTL_Thay_que/core/templates/order.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-6 text-3xl">Complete your order</h1>
{% load cart_tags %}
<div class="space-y-6">
    {% for book in cart.cart_book %}
        <div class="p-6 flex bg-gray-100 rounded-xl">
            <div class="pr-6">
                <img src="{{ book.image }}" class="w-20 rounded-xl">
            </div>

            <div>
                <p class="text-2xl">{{ book.title }}</p>
                <p class="text-xl text-gray-500">Đơn giá {{ book.price|number_format }} đ</p>
                <p class="text-xl text-gray-500"> Số lượng: {{ book.quantity }}</p>
                <p class="text-xl text-green-500"> Thành tiền: {{ book.total_price|number_format }} đ</p>
            </div>
        </div>
    {% endfor %}

    {% for clothes in cart.cart_clothes %}
        <div class="p-6 flex bg-gray-100 rounded-xl">
            <div class="pr-6">
                <img src="{{ clothes.image }}" class="w-20 rounded-xl">
            </div>

            <div>
                <p class="text-2xl">{{ clothes.name }}</p>
                <p class="text-xl text-gray-500">Đơn giá {{ clothes.price|number_format }} đ</p>
                <p class="text-xl text-gray-500"> Số lượng: {{ clothes.quantity }}</p>
                <p class="text-xl text-green-500"> Thành tiền: {{ clothes.total_price|number_format }} đ</p>
            </div>
        </div>
    {% endfor %}

    {% for mobile in cart.cart_mobile %}
        <div class="p-6 flex bg-gray-100 rounded-xl">
            <div class="pr-6">
                <img src="{{ mobile.image }}" class="w-20 rounded-xl">
            </div>

            <div>
                <p class="text-2xl">{{ mobile.name }}</p>
                <p class="text-xl text-gray-500">Đơn giá {{ mobile.price|number_format }} đ</p>
                <p class="text-xl text-gray-500"> Số lượng: {{ mobile.quantity }}</p>
                <p class="text-xl text-green-500"> Thành tiền: {{ mobile.total_price|number_format }} đ</p>
            </div>
        </div>
    {% endfor %}
    <p class="text-3xl text-green-700 font-bold">Tổng tiền: {{ total_price|number_format }} đ</p>

    <form action="{% url 'customer:add-order' %}" method="POST" class="w-1/3 rounded-xl">
        {% csrf_token %}
        <label for="type_purchase">Type of purchase</label>
        <select name="type_purchase" class="w-full p-3 rounded-xl bg-yellow-200 mb-2">
            <option value="cash">Cash</option>
            <option value="paypal">Paypal</option>
        </select>
        <label for="mobile">Your address</label>
        <input type="text" name="mobile" class="w-full py-2 px-6 rounded-xl mb-2 border border-gray-500" placeholder="default {{ request.session.user.mobile }}">
        <label for="delivery_address">Your delivery address</label>
        <input type="text" name="delivery_address" class="w-full mb-2 py-2 px-6 rounded-xl border border-gray-500" placeholder="default {{ request.session.user.address }}">
        <input type="hidden" name="total_price" value="{{ total_price }}">
        <button type="submit" class="px-6 py-3 text-white bg-green-500 hover:bg-green-700 rounded-xl font-bold">Confirm order</button>
    </form>
</div>
{% endblock content %}

kien truc va tkpm/code tmp/BTL_Thay_que/core/templates/success.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>hóa đơn</title>
<script src="https://cdn.tailwindcss.com"></script>
<link
	href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
	rel="stylesheet"
	integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
	crossorigin="anonymous">
<script
	src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
	integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
	crossorigin="anonymous"></script>
<style>
table {
	border-collapse: collapse;
}

td {
	padding: 5px 10px;
}
.right-align {
    text-align: right;
}
</style>
</head>

<body>
    <div>
        <div class="text-center mt-5">
            <p class="font-bold text-3xl text-green-700">You've completed your order</p>
        </div>
        <div class="my-5 text-center">
            <a href="/"><p class="font-bold text-red-500 mt-5">back to home</p></a>
        </div>
    </div>
</body>

</html>