kien truc va tkpm/CODE/DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('product/', include('product.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
    path('clothes/', include('clothes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kien truc va tkpm/CODE/DjangoProject/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('<int:pk>/add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('carts/', views.carts, name='carts'),
]

kien truc va tkpm/CODE/DjangoProject/product/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail',)
]

kien truc va tkpm/CODE/DjangoProject/search/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.products, name='products'),
    path('voice/', views.productsByVoice, name='products-voice'),
]

kien truc va tkpm/CODE/DjangoProject/product/models.py
from django.db import models

from category.models import Category

class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True,
        help_text='Unique value for product page URL, created from name.', null=True)
    author = models.CharField(max_length=255, null=True)
    publisher = models.CharField(max_length=255, null=True)
    price = models.IntegerField(default=0)
    old_price = models.IntegerField(default=0)
    image = models.ImageField(upload_to='product_images', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_bestseller = models.BooleanField(default=False)
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category, related_name='products')

    class Meta:
        app_label = 'product'
        db_table = 'product'
        ordering = ['-created_at']
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

kien truc va tkpm/CODE/DjangoProject/search/models.py
from django.db import models

# Create your models here.

kien truc va tkpm/CODE/DjangoProject/product/views.py
from django.shortcuts import render, get_object_or_404

from product.models import Product

def detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = product.categories.first().products.exclude(pk=pk)
    return render(request, 'product/detail.html', {
        'product': product,
        'related_products': related_products,
    })

kien truc va tkpm/CODE/DjangoProject/search/views.py
from django.shortcuts import render
from django.db.models import Q

from category.models import Category
from clothes.models import Clothes
from mobile.models import Mobile
from product.models import Product

import speech_recognition as sr

def products(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    products = Product.objects.all()
    clothes = Clothes.objects.all()
    mobiles = Mobile.objects.all()
    
    if query:
        products = products.filter(Q(name__icontains=query))
        clothes = clothes.filter(Q(name__icontains=query))
        mobiles = mobiles.filter(Q(name__icontains=query))
    
    if category_id:
        category = Category.objects.get(pk=category_id)
        products = Product.objects.filter(categories=category)
    
    return render(request, 'search/products.html', {
        'products': products,
        'query': query,
        'clothes': clothes,
        'mobiles': mobiles,
        'categories': categories,
        'category_id': int(category_id),
    })

def productsByVoice(request):
    recognizer = sr.Recognizer()
    
    text = ''

    with sr.Microphone() as source:
        print("Đang nghe... (nói 'kết thúc' để dừng lại)")

        try:
            # Tự động điều chỉnh nền để loại bỏ tiếng ồn
            recognizer.adjust_for_ambient_noise(source)
            
            audio_data = recognizer.listen(source, timeout=2)
            print("Đã nghe xong. Đang nhận dạng...")

            text = recognizer.recognize_google(audio_data, language="vi-VN")
            print("Văn bản nhận dạng từ giọng nói: {}".format(text))

        except sr.UnknownValueError:
            print("Không thể nhận dạng giọng nói")
        except sr.RequestError as e:
            print("Lỗi khi gửi yêu cầu đến API Google: {}".format(e))
        except sr.WaitTimeoutError:
            print("Hết thời gian chờ. Không có âm thanh được nghe.")

    # Kiểm tra nếu text là None hoặc trống thì gán giá trị khoảng trắng
    text = text or ''

    products = Product.objects.all()
    clothes = Clothes.objects.all()
    mobiles = Mobile.objects.all()
    products = products.filter(Q(name__icontains=text))
    clothes = clothes.filter(Q(name__icontains=text))
    mobiles = mobiles.filter(Q(name__icontains=text))
    categories = Category.objects.all()
    category_id = request.GET.get('category', 0)
    
    return render(request, 'search/products.html', {
        'products': products,
        'text': text,
        'clothes': clothes,
        'mobiles': mobiles,
        'categories': categories,
        'category_id': int(category_id),
    })

kien truc va tkpm/CODE/DjangoProject/templates/search/products.html
{% extends 'base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'search:products' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>
            <div class="mt-3 py-6">
                <a href="{% url 'search:products-voice' %}" class="mt-2 py-4 px-8 text-lg bg-red-500 text-white rounded-xl">Search-voice</a>
            </div>
            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'search:products' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'search:products' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
        </div>

        <div class="col-span-3">
            {% if text %}
                <h2 class="mb-12 text-2xl text-center mt-3">Kết quả tìm kiếm cho từ khóa "{{ text }}"</h2>
            {% endif %}

            {% if query %}
                <h2 class="mb-12 text-2xl text-center mt-3">Kết quả tìm kiếm cho từ khóa "{{ query }}"</h2>
            {% endif %}

            <div class="grid grid-cols-3 gap-3">
                {% for product in products %}
                    <div>
                        <a href="{% url 'product:detail' product.id %}">
                            <div>
                                <img src="{{ product.image.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ product.name }}</h2>
                                <p class="text-gray-500">Price: {{ product.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}


                {% for cloth in clothes %}
                    <div>
                        <a href="#">
                            <div>
                                <img src="{{ cloth.image.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ cloth.name }}</h2>
                                <p class="text-gray-500">Price: {{ cloth.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

                {% for mobile in mobiles %}
                    <div>
                        <a href="#">
                            <div>
                                <img src="{{ mobile.image.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ mobile.name }}</h2>
                                <p class="text-gray-500">Price: {{ mobile.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}